version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-codepipeline-manual-approval-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tar2xdp3r0js"
s3_prefix = "sns-codepipeline-manual-approval-poc"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
